[package]
name = "StudentMarketplace"
version = "1.0.0"
authors = []

[addresses]
StudentMarketplace = '0x674fb3a275e72e5d742f6b9b40e5b7344d160d89dcfcee54153ad5074fbf4100'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]